import tensorflow as tf
import numpy as np

model = None
output_class = ["Batteries", "Clothes", "E-waste", "Glass", "Metal", "Organic", "Paper", "Plastic"]
data = {
"Batteries":
	["Battery recycling is a practice focused on decreasing the disposal of batteries as municipal solid waste. Batteries contain various heavy metals and toxic chemicals, and disposing of them using the same method as regular household waste has led to concerns about potential soil contamination and water pollution. <br><br> The majority of battery types are capable of being recycled. However, certain batteries are recycled more easily than others. For instance, lead-acid automotive batteries (nearly 90% are recycled) and button cells (due to the value and toxicity of their components) are readily recycled. Rechargeable batteries like nickel-cadmium (Ni-Cd), nickel metal hydride (Ni-MH), lithium-ion (Li-ion), and nickel-zinc (Ni-Zn) can also be recycled. Currently, there is no cost-effective recycling solution available for disposable alkaline batteries, although guidelines for consumer disposal differ from region to region.",
	"4XOAGNzWvqY", "UARCW5haP34"],
"Clothes":
	["Textile recycling involves the recovery of fibers, yarns, or fabrics and the subsequent reprocessing of these textile materials into practical items. Various sources provide textile waste, which is then sorted and processed based on its condition, composition, and potential resale value. The outcome of this process can range from the creation of energy and chemicals to the production of new clothing items.<br><br>Given the recent surge in excessive consumption and waste generation within the global fashion culture, textile recycling has emerged as a central focus of worldwide sustainability endeavors. The phenomenon of \"fast fashion\" driven by globalization has caused many consumers to perceive clothing as disposable due to its increasingly affordable cost. Advancements in recycling technology have enabled the textile industry to manufacture significant quantities of products while depleting natural resources.",
	"Bhi7S06pwv4", "7i0QMnz4ExY"],
"E-waste":
	["Electronic waste, commonly referred to as e-waste, encompasses discarded electrical or electronic devices. Electronics that are no longer in use and are intended for refurbishment, reuse, resale, salvage recycling through material recovery, or proper disposal fall under the category of e-waste. In developing nations, the informal handling of e-waste can have detrimental impacts on human health and the environment.<br><br>Various components of electronic scrap, such as central processing units (CPUs), contain potentially hazardous substances like lead, cadmium, beryllium, or brominated flame retardants. The recycling and disposal processes of e-waste can pose significant health risks to workers and their communities.<br><br>E-waste, or electronic waste, arises when electronic products are discarded at the conclusion of their useful lifespan. The rapid advancement of technology and the consumer-oriented society contribute to the substantial accumulation of e-waste every minute.",
	"aUwFXDLOFO0","w0ikFMTuS9c"],
"Glass":
	["Glass recycling involves the transformation of discarded glass into usable items. Glass that has been crushed and is ready for remelting is known as cullet. Cullet comes in two varieties: internal and external. Internal cullet is comprised of defective products identified and rejected through quality control during the industrial glass manufacturing process, as well as product transition phases (like changes in thickness or color) and manufacturing offcuts. External cullet is waste glass that has been gathered or reprocessed with the intention of recycling. External cullet, whether pre- or post-consumer, is categorized as waste. In the context of end-of-waste, the term \"cullet\" will always refer to external cullet.<br><br>For glass waste to be recycled, it must undergo purification and cleaning to eliminate contaminants. Additionally, depending on its intended application and the capabilities of local processing facilities, glass might need to be sorted into various colors. Many recycling centers collect different colors of glass separately because glass retains its color even after recycling.",
	"fp_vfaGP5TI", "6R8YObQbE88"],
"Metal":
	["A variety of metals, in substantial quantities, are employed in industrial operations on a daily basis. With the advent of the industrial revolution, our consumption levels have surged due to the mass production of goods and the resultant reduction in unit costs.<br><br>The most widely consumed metal globally is aluminum, closely followed by copper, zinc, lead, and nickel. Additionally, valuable materials such as gold find utility in our computers and other electronic devices.<br><br>Metals play a pivotal role in maintaining our living standards. However, metals are finite resources. As the global population continues to grow, the demand for metal-based goods will also escalate, potentially posing a significant challenge of metal depletion in the future.<br><br>Addressing the impending issue of metal depletion necessitates the implementation of effective strategies. Among these strategies, metal recycling emerges as a promising solution.",
	"lWjguKOVOQs", "rgEEXhbar3A"],
"Organic":
	["Organic waste comprises materials derived from living organisms. Various kinds of organic waste exist, spanning municipal solid waste, industrial solid waste, agricultural waste, and wastewater. While organic wastes are commonly disposed of alongside other wastes in landfills or incinerators, their biodegradability allows for certain types to be suitable for composting and land application.<br><br>Municipal solid waste contains organic materials like food, paper, wood, sewage sludge, and yard waste. Due to recent landfill capacity shortages, there's a growing number of municipal composting sites for yard waste nationwide, along with an increasing trend of citizens composting yard waste in their own backyards. To a more limited extent, mixed municipal waste composting is also being practiced, with efforts to remove inorganic materials before composting.<br><br>Food waste from restaurants and grocery stores is often disposed of via garbage disposals, leading it to become a component of wastewater and sewage sludge.",
	"s5QJJ9Na9ys", "2I8Tjb4Fy-Q"],
"Paper":
	["Paper recycling is the method through which waste paper is transformed into fresh paper products. This process boasts several significant advantages: It prevents waste paper from occupying people's living spaces and emitting methane during decomposition. Given that paper fiber contains carbon (initially absorbed by the tree it originated from), recycling serves to retain carbon for an extended period and prevents its release into the atmosphere. In the United States, approximately two-thirds of all paper products are now reclaimed and recycled, although not all of it is turned into new paper. As the fibers become excessively short through multiple cycles of processing, they become unfit for new paper production, prompting the inclusion of virgin fiber (sourced from sustainably cultivated trees) in the pulp formulation.<br><br>Paper recycling encompasses the procedures of reprocessing discarded paper for renewed usage. Waste papers are sourced from a variety of origins including paper mill scraps, discarded paper materials, and paper items discarded by consumers after use. Notable examples of papers frequently recycled include old newspapers and magazines.",
	"jAqVxsEgWIM", "AFWogncmqoQ"],
"Plastic":
	["Plastic recycling involves the retrieval and reprocessing of discarded or waste plastic material to create useful products. Unfortunately, due to misleading symbols on plastic packaging and numerous technical challenges, the rate of plastic recycling is dishearteningly low, with less than 10% of plastic having been recycled. Unlike the lucrative recycling of metals, and similarly reflecting the modest value of glass recycling, the recycling of plastic polymers is often more complex due to their low density and value.<br><br>The sorting and processing of plastics are handled by materials recovery facilities. However, up until 2019, these facilities have struggled to significantly contribute to the plastic supply chain due to economic limitations. Since the 1970s, the plastics industry has been aware of the impracticality of recycling most plastics due to these constraints. Despite this knowledge, the industry has advocated for expanded recycling while concurrently increasing the production of virgin plastic.",
	"RDFBbxMDi1U", "I_fUpP-hq3A"]
}


def load_artifacts():
    global model
    model = tf.keras.models.load_model("wasteClassificationModel.h5")

def classify_waste(image_path):
	global model, output_class
	test_image = tf.keras.preprocessing.image.load_img(image_path, target_size=(224, 224))
	test_image = tf.keras.preprocessing.image.img_to_array(test_image) / 255
	test_image = np.expand_dims(test_image, axis = 0)
	predicted_array = model.predict(test_image)
	predicted_value = output_class[np.argmax(predicted_array)]
	return predicted_value, data[predicted_value][0], data[predicted_value][1], data[predicted_value][2]

